services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ../laravel-app:/var/www
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    working_dir: /var/www
    volumes:
      - ../laravel-app:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
